version: '3.8'
services:
  server:
    image: rbc/stockapi
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/db_example?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysql
  mysql:
    image: mysql
    networks: 
      - springmysql-net
    environment:
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=ThePassword
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
networks:
  springmysql-net: